apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-v1
  name: redis-v1
  namespace: pawel
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-v1
  sessionAffinity: None
  type: ClusterIP
