apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-v1
  namespace: pawel
data:
  launch.sh: |
    #!/bin/sh

    PASSWORD=$(cat /etc/redis-passwd/passwd)

    if [[ "${HOSTNAME}" == "redis-v1-0" ]]; then
      redis-server --requirepass ${PASSWORD}
    else
      redis-server  --slaveof redis-v1-0.redis 6379  \
                    --masterauth ${PASSWORD}      \
                    --requirepass ${PASSWORD}
    fi
