apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-v1
  name: frontend-v1
  namespace: pawel
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-v1
  type: ClusterIP
